spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      # api-key: test
  application:
    name: testing-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        tool:
          hbm2ddl: debug
lolomo:
  initialize-shows: false
